### ISSUE TITLE
nc_time_axis 1.0.2

### ISSUE THREAD

**Issue by bjlittle** [conda-forge/nc_time_axis-feedstock#15]
Is it now not possible to get the **last** `nc_time_axis` version `1.0.2`, rather than the **first** `nc-time-axis` version `1.1.0` from `conda-forge` ?

**Comment by bjlittle** [comment]
Ping @pdearnshaw

**Comment by ocefpaf** [comment]
They are in a label "renamed," see https://anaconda.org/conda-forge/nc_time_axis/files

One conda install them with `conda-forge/label/renamed::nc_time_axis` on env files or
`conda install --channel conda-forge/label/renamed nc_time_axis`.
